name: Build

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'alpine/**'
      - 'debian/**'
      - versions.json
  workflow_dispatch:

env:
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
  SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set matrix
        id: set-matrix
        run: |
          JSON=$(cat ./versions.json)
          echo "matrix=$(jq -cM . <<< ${JSON})" >> $GITHUB_OUTPUT

  image:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        image: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Send Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        id: slack
        with:
          fields: |
            {STATUS}
            {REF}
            klei-tools version: ${{ matrix.image.klei_tools_version }}
            ktools version: ${{ matrix.image.ktools_version }}
          status: in-progress
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Prepare Docker meta for an Alpine image
        uses: docker/metadata-action@v4
        id: alpine-meta
        with:
          images: |
            ${{ github.repository_owner }}/dst-mod
            ghcr.io/${{ github.repository_owner }}/dst-mod
          labels: |
            maintainer=victor@popkov.me
          tags: |
            type=raw,value=alpine
      - name: Build an Alpine image
        uses: docker/build-push-action@v3
        with:
          build-args: DS_KTOOLS_VERSION=${{ matrix.image.ktools_version }}
          cache-from: type=registry,ref=${{ github.repository_owner }}/dst-mod:alpine
          cache-to: type=inline
          context: .
          file: ${{ matrix.image.root }}/alpine/Dockerfile
          labels: ${{ steps.alpine-meta.outputs.labels }}
          platforms: linux/amd64
          pull: true
          push: ${{ !env.ACT && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.alpine-meta.outputs.tags }}
      - name: Prepare Docker meta for a Debian image
        uses: docker/metadata-action@v4
        id: debian-meta
        with:
          flavor: |
            latest=${{ matrix.image.latest }}
          images: |
            ${{ github.repository_owner }}/dst-mod
            ghcr.io/${{ github.repository_owner }}/dst-mod
          labels: |
            maintainer=victor@popkov.me
          tags: |
            type=raw,value=debian
      - name: Build a Debian image
        uses: docker/build-push-action@v4
        with:
          build-args: DS_KLEI_TOOLS_VERSION=${{ matrix.image.klei_tools_version }}
          cache-from: type=registry,ref=${{ github.repository_owner }}/dst-mod:debian
          cache-to: type=inline
          context: .
          file: ${{ matrix.image.root }}/debian/Dockerfile
          labels: ${{ steps.debian-meta.outputs.labels }}
          platforms: linux/amd64
          pull: true
          push: ${{ !env.ACT && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.debian-meta.outputs.tags }}
      - name: Update Slack notification
        uses: codedsolar/slack-action@v1
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          fields: |
            {STATUS}
            {REF}
            klei-tools version: ${{ matrix.image.klei_tools_version }}
            ktools version: ${{ matrix.image.ktools_version }}
          status: ${{ job.status }}
          timestamp: ${{ steps.slack.outputs.slack-timestamp }}
