name: CI

on:
  push:
    branches:
      - develop
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    if: always()
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set a job-wide environment variables
        run: |
          echo "::set-env name=BRANCH_NAME::${GITHUB_REF##*/}"
          echo '::set-env name=GITHUB_JOB_NAME::lint'
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install Prettier
        run: yarn global add prettier
      - name: Lint
        continue-on-error: true
        id: lint
        run: |
          # Prettier
          export LINT_ISSUES_PRETTIER=$(prettier --list-different . | wc -l)
          export LINT_ISSUES_PRETTIER=$((LINT_ISSUES_MD < 0 ? 0 : LINT_ISSUES_MD))

          # Issues
          export LINT_ISSUES="${LINT_ISSUES_PRETTIER}"

          # env
          echo "::set-env name=LINT_ISSUES::${LINT_ISSUES}"
          echo "::set-env name=LINT_ISSUES_PRETTIER::${LINT_ISSUES_PRETTIER}"

          # lint
          prettier --check . || true

          # status
          if [ "${LINT_ISSUES_PRETTIER}" -eq 0 ]; then
            echo '::set-output name=status::success'
            exit 0
          else
            echo '::set-output name=status::failure'
            exit 1
          fi
      - name: Preparing success Slack notification
        if: success()
        run: echo "::set-env name=SLACK_CUSTOM_PAYLOAD::${SLACK_CUSTOM_PAYLOAD}"
        env:
          SLACK_CUSTOM_PAYLOAD: '{"channel":"docker-dst-mod","attachments":[{"color":"#2eb886","fallback":"GitHub Actions {{ GITHUB_WORKFLOW }} workflow {{ GITHUB_JOB_NAME }} job of {{ GITHUB_REPOSITORY }}@{{ BRANCH_NAME }} by {{ GITHUB_ACTOR }} has passed with no issues","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"GitHub Actions *<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}|{{ GITHUB_WORKFLOW }}>* workflow *{{ GITHUB_JOB_NAME }}* job of *<https://github.com/{{ GITHUB_REPOSITORY }}|{{ GITHUB_REPOSITORY }}>@<https://github.com/{{ GITHUB_REPOSITORY }}/tree/{{ BRANCH_NAME }}|{{ BRANCH_NAME }}>* by *{{ GITHUB_ACTOR }}* has passed with no issues"}}]}]}'
      - name: Preparing failure Slack notification
        if: failure()
        run: echo "::set-env name=SLACK_CUSTOM_PAYLOAD::${SLACK_CUSTOM_PAYLOAD}"
        env:
          SLACK_CUSTOM_PAYLOAD: '{"channel":"docker-dst-mod","attachments":[{"color":"#ed2f00","fallback":"GitHub Actions {{ GITHUB_WORKFLOW }} workflow {{ GITHUB_JOB_NAME }} job of {{ GITHUB_REPOSITORY }}@{{ BRANCH_NAME }} by {{ GITHUB_ACTOR }} has failed with {{ LINT_ISSUES }} issues","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"GitHub Actions *<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}|{{ GITHUB_WORKFLOW }}>* workflow *{{ GITHUB_JOB_NAME }}* job of *<https://github.com/{{ GITHUB_REPOSITORY }}|{{ GITHUB_REPOSITORY }}>@<https://github.com/{{ GITHUB_REPOSITORY }}/tree/{{ BRANCH_NAME }}|{{ BRANCH_NAME }}>* by *{{ GITHUB_ACTOR }}* has failed with *{{ LINT_ISSUES }}* issues"}},{"type":"section","fields":[{"type":"mrkdwn","text":"*Prettier*:\n{{ LINT_ISSUES_PRETTIER }}"}]}]}]}'
      - name: Sending Slack notification
        uses: Ilshidur/action-slack@master
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CODEDSOLAR }}
